// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBwHk4Xlou0Uld5yYYahWxAIDNR12ElEyg',
    appId: '1:1034344193488:android:88a2f23670e552f1fa6dd5',
    messagingSenderId: '1034344193488',
    projectId: 'sundayselfie-8cd4a',
    storageBucket: 'sundayselfie-8cd4a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDARsrSPf2E8-JVWG3NR44XMc1v_ksUycw',
    appId: '1:1034344193488:ios:acfa9ad36329e8e0fa6dd5',
    messagingSenderId: '1034344193488',
    projectId: 'sundayselfie-8cd4a',
    storageBucket: 'sundayselfie-8cd4a.firebasestorage.app',
    iosClientId: '1034344193488-uv03ghs316rhe1dujdtftdqalunbvprk.apps.googleusercontent.com',
    iosBundleId: 'com.example.sundaySelfie',
  );
}
