// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBf_ftOf-sUz5YrDqP6Dt1vU3M1nD5RAtI',
    appId: '1:1034344193488:web:8133864032418a64fa6dd5',
    messagingSenderId: '1034344193488',
    projectId: 'sundayselfie-8cd4a',
    authDomain: 'sundayselfie-8cd4a.firebaseapp.com',
    storageBucket: 'sundayselfie-8cd4a.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBwHk4Xlou0Uld5yYYahWxAIDNR12ElEyg',
    appId: '1:1034344193488:android:6bae04914dcd86e6fa6dd5',
    messagingSenderId: '1034344193488',
    projectId: 'sundayselfie-8cd4a',
    storageBucket: 'sundayselfie-8cd4a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDARsrSPf2E8-JVWG3NR44XMc1v_ksUycw',
    appId: '1:1034344193488:ios:a01b81054315c817fa6dd5',
    messagingSenderId: '1034344193488',
    projectId: 'sundayselfie-8cd4a',
    storageBucket: 'sundayselfie-8cd4a.firebasestorage.app',
    iosClientId:
        '1034344193488-8emnuhos864bnirt4263p1984sp9cm36.apps.googleusercontent.com',
    iosBundleId: 'app.sundayselfie',
  );
}
